import PDFDocument from "pdfkit";

export type PassDetails = { bookingId:string; fullName:string; mobile:string; date:string; startTime:string; endTime:string; persons:number; approvedAt:string|null };
export type ReportRow = PassDetails & { username:string; email:string; status:string; createdAt:string };
const saffron="#8f2f0c", gold="#fbbf24", ink="#2d221f", muted="#70635d";
const inDate=(v:string)=>new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${v}T00:00:00`));
const inTime=(v:string)=>new Date(`2000-01-01T${v}`).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"});
const issued=(v:string|null)=>v?new Date(v).toLocaleString("en-IN"):"-";

function resultBuffer(doc:PDFKit.PDFDocument){return new Promise<Buffer>((resolve,reject)=>{const chunks:Buffer[]=[];doc.on("data",(c:Buffer)=>chunks.push(c));doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject)})}
function background(doc:PDFKit.PDFDocument,heading:string,subtitle:string){const {width,height}=doc.page;doc.rect(0,0,width,height).fill("#fffaf4");doc.rect(0,0,width,176).fill(saffron);doc.fillColor("#d97706");for(let x=15;x<width;x+=24)for(let y=14;y<176;y+=24)doc.circle(x,y,1.1).fill();doc.fillColor(gold).font("Helvetica-Bold").fontSize(11).text("KHAIRATABAD GANESH DARSHANAM",42,35);doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(27).text(heading,42,64);doc.fillColor("#fde68a").font("Helvetica").fontSize(11).text(subtitle,42,103);doc.fillColor(gold).circle(width-73,78,34).fill();doc.fillColor(saffron).font("Helvetica-Bold").fontSize(23).text("OM",width-105,71,{width:64,align:"center"})}
function field(doc:PDFKit.PDFDocument,x:number,y:number,label:string,value:string,width=210){doc.fillColor(muted).font("Helvetica-Bold").fontSize(8).text(label.toUpperCase(),x,y,{width});doc.fillColor(ink).font("Helvetica-Bold").fontSize(12).text(value,x,y+14,{width})}

export async function makeBookingPassPdf(data:PassDetails){const doc=new PDFDocument({size:"A4",margin:0,info:{Title:`Ganesh Darshan Pass - ${data.bookingId}`,Author:"Khairatabad Ganesh Darshanam"}});const result=resultBuffer(doc);background(doc,"Approved Darshan Pass","Please present this pass at the Darshan entry point.");doc.roundedRect(40,150,515,500,18).fill("#ffffff");doc.fillColor(gold).roundedRect(40,150,515,7,3).fill();doc.fillColor(saffron).font("Helvetica-Bold").fontSize(9).text("BOOKING ID",68,190);doc.fillColor(saffron).font("Helvetica-Bold").fontSize(25).text(data.bookingId,68,207);doc.fillColor("#166534").roundedRect(417,190,104,27,14).fill();doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(10).text("APPROVED",417,199,{width:104,align:"center"});doc.strokeColor("#e7ded9").lineWidth(1).moveTo(68,255).lineTo(526,255).stroke();field(doc,68,284,"Devotee name",data.fullName);field(doc,323,284,"Mobile number",data.mobile,170);field(doc,68,365,"Darshan date",inDate(data.date));field(doc,323,365,"Darshan timing",`${inTime(data.startTime)} - ${inTime(data.endTime)}`,190);field(doc,68,446,"Number of persons",String(data.persons));field(doc,323,446,"Approved on",issued(data.approvedAt),190);doc.roundedRect(68,526,459,78,10).fill("#fff7ed");doc.fillColor(saffron).font("Helvetica-Bold").fontSize(10).text("IMPORTANT",86,543);doc.fillColor(ink).font("Helvetica").fontSize(10).text("Carry this pass and a valid photo ID. Entry is subject to on-site verification and the allotted time slot.",86,560,{width:422,lineGap:3});doc.fillColor(muted).font("Helvetica").fontSize(8).text("Official Khairatabad Ganesh Darshanam booking portal",40,703,{width:515,align:"center"});doc.end();return result}

function reportHeader(doc:PDFKit.PDFDocument,page:number){background(doc,"Booking Report",`Authorized administrative export - page ${page}`);const cols=[42,120,224,314,394,470],heads=["Booking ID","Devotee","Darshan","Persons","Status","Approved"];doc.roundedRect(34,153,527,27,6).fill("#fff1df");heads.forEach((h,i)=>doc.fillColor(saffron).font("Helvetica-Bold").fontSize(7).text(h,cols[i],163));return cols}
export async function makeAdminReportPdf(rows:ReportRow[]){const doc=new PDFDocument({size:"A4",layout:"landscape",margin:0,info:{Title:"Khairatabad Ganesh Darshanam Booking Report",Author:"Khairatabad Ganesh Darshanam"}});const result=resultBuffer(doc);let page=1,cols=reportHeader(doc,page),y=197;for(const row of rows){if(y>520){doc.addPage();page+=1;cols=reportHeader(doc,page);y=197}doc.fillColor("#f5eee9").rect(34,y-7,527,1).fill();const values=[row.bookingId,`${row.fullName}\n@${row.username}\n${row.mobile}`,`${inDate(row.date)}\n${inTime(row.startTime)} - ${inTime(row.endTime)}`,String(row.persons),row.status.toUpperCase(),issued(row.approvedAt)],widths=[73,94,80,50,62,85];values.forEach((v,i)=>doc.fillColor(ink).font(i===0?"Helvetica-Bold":"Helvetica").fontSize(7.5).text(v,cols[i],y,{width:widths[i],lineGap:2}));y+=44}if(!rows.length)doc.fillColor(muted).font("Helvetica").fontSize(13).text("No booking records found.",34,220,{width:527,align:"center"});doc.end();return result}
